export enum Event {
  accelerateActivePiece  = 'tetris.accelerateActivePiece',
  activePiecePositioned  = 'tetris.activePiecePositioned',
  animationEnd           = 'tetris.animationEnd',
  changeTheme            = 'tetris.changeTheme',
  deccelerateActivePiece = 'tetris.accelerateActivePiece',
  invalidMove            = 'tetris.invalidMove',
  moveActivePiece        = 'tetris.moveActivePiece',
  pause                  = 'tetris.pause',
  playfieldSettled       = 'tetris.playfieldSettled',
  rotateActivePiece      = 'tetris.rotateActivePiece',
  rowCleared             = 'tetris.rowCleared',
  rowComplete            = 'tetris.rowComplete',
  topOut                 = 'tetris.topOut',
};
